name: documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jinja2

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Clone and Install Pyxu-diffops repository
        run: |
          git clone https://github.com/dhamm97/pyxu-diffops.git
          cd pyxu-diffops
          python -m pip install .[dev]
          cd ../

      - name: Build HTML documentation
        run: |
          export TZ=UTC
          sphinx-build -b html -j auto -w build/html/WARNINGS.log pyxu-diffops/doc/ pyxu-diffops/build/html/

      - name: Remove Pyxu-diffops repository
        run: |
          mv pyxu-diffops/build/html/* ./
          rm -rf pyxu-diffops

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          touch .nojekyll
          git add -A
          git commit -m "Update generated HTML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: |
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}